BIRTHDAY_WISH_PACK_1 = [
    "Happy, happy birthday! You deserve all the cakes, love, hugs and happiness today. Enjoy your day my friend! May God shower you with blessings today and always.",
    "Happy Birthday Wishes For Him",
    "On your special day, I wish you good luck. I hope this wonderful day will fill up your heart with joy and blessings. Have a fantastic birthday, celebrate the happiness ...",
    "Wishing you a day filled with happiness and a year filled with joy. Happy birthday! Sending you smiles for every moment of your special day Have a wonderful time and a very happy birthday! Hope your special day brings you all that your heart desires!",
    "Have a wonderful birthday, my dear! You are a very special person and you deserve all the happiness life can give you. Happy birthday to the most incredible, selfless human being ever to exist! I am so blessed to have you in my life, my dear!",
    "Stay blessed and enjoy your day to the fullest. May God almighty bless you with a life full of joy and happiness. And may you always find favor in His eyes. Have a happy birthday.",
    "Let Jesus guide you in all your plans, In all your dreams, In all your wish to happen in your life. God bless. I ask God to bless you, to guide you, to keep you safe, to give you peace, to give u joy and love all d time. Take Care.",
    "Happy Birthday! May God bless you today on your birthday and every day after. May you be comforted by His presence in your life, and always follow His guiding light. Amen. I pray on your birthday that your faith in God continues to grow as you grow older, and that you find comfort in God's love for you.",
    "Write something encouraging Write something that will encourage someone in a time of loneliness. Maybe an write inspiring anekdote, recite a poem that inspires you or share a life lesson. Something that might seem small to you can have a big influence on a stranger, so go with your gut.",
    "The wishes range from beautifully crafted birthday messages for best friends and friends you've known for a long time to short and sweet ...",
    "Wishing you a day soft as silk, white as milk, sweet as honey and full of money. may all your dreams come true. Dear Friend, Happy Birthday to you.",
    "happy Birthday To My Fantastic Friend. I hope this is the beginning of the best year ever!Have a great day!",
    "My dear friend, having you as my friend is a privilage to me. May every moment of your life be as wonderful as our friendship. Happy birthday! You ...",
    "A simple celebration, a gathering of friends; here is wishing you great happiness, a joy that never ends. Wish u a very happy birthday friend may u get all that u ...",
    "Whether you know a friend or family member who is having a birthday, our happy birthday wishes are the perfect choice for you. Wish them a friendly, heartfelt or ...",
    "Birthday wishes for friends to wish your friend on his\/her birthday. Wish your best friend a very happy birthday with these perfect birthday messages.",
    "Birthday Messages to the Friend. Without our friends, life would be very dull. It is a wonderful thing when people from different backgrounds can come together and ...",
    "On your birthday I wish you success and endless happiness. May your sweet smile ... Happy Birthday",
    "I wish the same for you, on your birthday, dear friend. May you have the best time ever with your friends. May you receive lots of love and care.",
    "Wishing you a day that is as special in every way as you are. Happy Birthday.",
    "You are my friend. You are always ...",
    "A big list of birthday wishes for a best friend.",
    "It was Your Birthday Today on Your Birthday, I am here to Wish You HAPPY BIRTHDAY TO MY SWEET FRIEND. It is the day of a CAKE   many CANDLES",
    "Birthday Wishes for Friends  What a year!  Happy birthday best friend!  Happy birthday!  May all your dreams and wishes come true, you deserve it ...",
    "Birthday Wishes For A Friend. Birthdays are a special occasion celebrating your entry into this wonderful world. Enjoy your special day and ...",
    "A friend like you is more priceless than the most beautiful diamond. You are not only strong and wise, but kind and thoughtful as well.",
    "You are such a special blessing to me and I wish you a wonderful Birthday filled with love, joy and all good things you enjoy most!",
    "I'm so glad to have such an amazing person in my life! Thank you for being always there for me. May your special day bring you a huge joy and a true happiness!",
    "Let Jesus guide you in all your plans, In all your dreams, In all your wish to happen in your life. God bless. I ask God to bless you, to guide you, to keep you safe, to give you peace, to give u joy and love all d time. Take Care.",
    "Lord please give my treasured friend love and blessings without end. Bring contentment in her life; Comfort her in times of strife. Always keep her safe, secure; Let her path to You be sure. Lord, I pray my friend will be close to you, eternally.",
    "Happy birthday to my crazy, fun, fabulous best friend! I love you to the moon and back and am so grateful for your friendship and all the fun times ...",
    "Meaningful Birthday Messages. Sending you nothing but positive vibes on your birthday. I hope you know how much you're loved today, ...",
    "Birthdays come around every year, but friends like you only come once in a lifetime. I'm so glad you came ...",
    "1. Happy Birthday To My Fantastic Friend. I hope this is the beginning of the best year ever!Have a great day!",
    "Happy Birthday, best friend.  Happy Birthday to my best friend!  Best friends like you come along once in a lifetime.  Happy Birthday to the most awesome best ...",
    "Happy Birthday to Someone Special. 1, 2, 3. Blow out your candles and make a wish for you and me. May we always be as ...",
    "Birthday wishes for friends to wish your friend on his\/her birthday. Wish your best friend a very happy birthday with these perfect birthday messages.",
    "You are a true friend, so please don't change ever! Happy Birthday, and may every wish you have come ...",
    "Happy Birthday. Live beautifully, love generously, laugh freely. Thanks for being a fantastic friend. I hope ...",
    "Wishing you a day that is as special in every way as you are. Happy Birthday.",
    "You are my friend.",
    "A best friend in my life but much more like family at heart, you are more special to me than I'll ever be able to put into words. I don't know what I did to deserve ...",
    "Wishing my friend a very happy birthday and you don't need to speak it out loud that I'm your best friend too. Love you, dear. Thanks for being a ...",
    "With you I share a truly special and unique bond. Friends like you only come once in a lifetime. I'm so glad you came into my life. Happy Birthday, ...",
    "Happy birthday, dear friend! I wish you to not be afraid of bold choices and keep doing crazy stuff, because life is about trying things that terrify you. May this ...",
    "Happy Birthday Wishes for a Friend. May God shower you with blessings today and always. Happy birthday wishes to my friend! Every step of the way you were ...",
    "Beautiful Happy Birthday Wishes, Quotes, Messages for friends and family.  Wish you a many many happy returns of the day.  On your birthday I wish you success ...",
    "I hope you never stop enjoying the small things in life. Because that's what makes life worth living.",
    "I feel so lucky to have you as my friend.",
    "Happy Birthday to you, my Friend!  ~ If I were a bird, I'd sing for you.  ~ For your Birthday, I'd love to give you a beach where we could make wishes on starfish",
    "Happy birthday may you be blessed with fulfilled dreams and happy thoughts. Birthday Messages to the Friend. Without our friends, life would be very dull.",
    "Happy birthday to my dearest friend, you have always been there for me and I will always be there for you.",
    "Happy birthday! Let's party, BFF! I wish you a very glorious and very bright life ahead. May your life be full of massive success. Our friendship is ...",
    "Funny wishes, touching quotes and meaningful messages let you say happy birthday best friend in a truly special and emotional way to make ...",
    "Happy birthday! I miss you! 15. I miss your smile and everything about you. Here's to wishing you a very happy birthday, best friend!",
    "Happy birthday, my friend. If I could create my life all over again, and pick one friend, it would be you. You are fearless, and I admire you! Thank ...",
    "Today is the start of something beautiful. A new dawn and a fresh start. Exploit and conquer",
    "Happy Birthday, my dear friend! ",
    "Count your life by smiles, not tears. Count your age by friends, not years. I wish you a Happy birthday to cute girlfriend!Happy birthday!",
    "Happy Birthday, I can't imagine my life without your special friendship.  Your friendship means the world to me.",
    "Happy birthday to my ride or die my best friend.  Best friends are never told that they are best friends. They just know and I probably don't need to say it out loud.",
]

BIRTHDAY_WISH_PACK_2 = [
    "Happy, happy birthday! You deserve all the cakes, love, hugs and happiness today. Enjoy your day my friend! May God shower you with blessings today and always.",
    "Happy Birthday Wishes For Him",
    "On your special day, I wish you good luck. I hope this wonderful day will fill up your heart with joy and blessings. Have a fantastic birthday, celebrate the happiness ...",
    "Wishing you a day filled with happiness and a year filled with joy. Happy birthday! Sending you smiles for every moment of your special day Have a wonderful time and a very happy birthday! Hope your special day brings you all that your heart desires!",
    "Have a wonderful birthday, my dear! You are a very special person and you deserve all the happiness life can give you. Happy birthday to the most incredible, selfless human being ever to exist! I am so blessed to have you in my life, my dear!",
    "Stay blessed and enjoy your day to the fullest. May God almighty bless you with a life full of joy and happiness. And may you always find favor in His eyes. Have a happy birthday.",
    "Let Jesus guide you in all your plans, In all your dreams, In all your wish to happen in your life. God bless. I ask God to bless you, to guide you, to keep you safe, to give you peace, to give u joy and love all d time. Take Care.",
    "Happy Birthday! May God bless you today on your birthday and every day after. May you be comforted by His presence in your life, and always follow His guiding light. Amen. I pray on your birthday that your faith in God continues to grow as you grow older, and that you find comfort in God's love for you.",
    "Write something encouraging Write something that will encourage someone in a time of loneliness. Maybe an write inspiring anekdote, recite a poem that inspires you or share a life lesson. Something that might seem small to you can have a big influence on a stranger, so go with your gut.",
    "The wishes range from beautifully crafted birthday messages for best friends and friends you've known for a long time to short and sweet ...",
    "Wishing you a day soft as silk, white as milk, sweet as honey and full of money. may all your dreams come true. Dear Friend, Happy Birthday to you.",
    "happy Birthday To My Fantastic Friend. I hope this is the beginning of the best year ever!Have a great day!",
    "My dear friend, having you as my friend is a privilage to me. May every moment of your life be as wonderful as our friendship. Happy birthday! You ...",
    "A simple celebration, a gathering of friends; here is wishing you great happiness, a joy that never ends. Wish u a very happy birthday friend may u get all that u ...",
    "Whether you know a friend or family member who is having a birthday, our happy birthday wishes are the perfect choice for you. Wish them a friendly, heartfelt or ...",
    "Birthday wishes for friends to wish your friend on his\/her birthday. Wish your best friend a very happy birthday with these perfect birthday messages.",
    "Birthday Messages to the Friend. Without our friends, life would be very dull. It is a wonderful thing when people from different backgrounds can come together and ...",
    "On your birthday I wish you success and endless happiness. May your sweet smile ... Happy Birthday",
    "I wish the same for you, on your birthday, dear friend. May you have the best time ever with your friends. May you receive lots of love and care.",
    "Wishing you a day that is as special in every way as you are. Happy Birthday.",
    "You are my friend. You are always ...",
    "A big list of birthday wishes for a best friend.",
    "It was Your Birthday Today on Your Birthday, I am here to Wish You HAPPY BIRTHDAY TO MY SWEET FRIEND. It is the day of a CAKE   many CANDLES",
    "Birthday Wishes for Friends  What a year!  Happy birthday best friend!  Happy birthday!  May all your dreams and wishes come true, you deserve it ...",
    "Birthday Wishes For A Friend. Birthdays are a special occasion celebrating your entry into this wonderful world. Enjoy your special day and ...",
    "A friend like you is more priceless than the most beautiful diamond. You are not only strong and wise, but kind and thoughtful as well.",
    "You are such a special blessing to me and I wish you a wonderful Birthday filled with love, joy and all good things you enjoy most!",
    "I'm so glad to have such an amazing person in my life! Thank you for being always there for me. May your special day bring you a huge joy and a true happiness!",
    "Let Jesus guide you in all your plans, In all your dreams, In all your wish to happen in your life. God bless. I ask God to bless you, to guide you, to keep you safe, to give you peace, to give u joy and love all d time. Take Care.",
    "Lord please give my treasured friend love and blessings without end. Bring contentment in her life; Comfort her in times of strife. Always keep her safe, secure; Let her path to You be sure. Lord, I pray my friend will be close to you, eternally.",
    "Happy birthday to my crazy, fun, fabulous best friend! I love you to the moon and back and am so grateful for your friendship and all the fun times ...",
    "Meaningful Birthday Messages. Sending you nothing but positive vibes on your birthday. I hope you know how much you're loved today, ...",
    "Birthdays come around every year, but friends like you only come once in a lifetime. I'm so glad you came ...",
    "1. Happy Birthday To My Fantastic Friend. I hope this is the beginning of the best year ever!Have a great day!",
    "Happy Birthday, best friend.  Happy Birthday to my best friend!  Best friends like you come along once in a lifetime.  Happy Birthday to the most awesome best ...",
    "Happy Birthday to Someone Special. 1, 2, 3. Blow out your candles and make a wish for you and me. May we always be as ...",
    "Birthday wishes for friends to wish your friend on his\/her birthday. Wish your best friend a very happy birthday with these perfect birthday messages.",
    "You are a true friend, so please don't change ever! Happy Birthday, and may every wish you have come ...",
    "Happy Birthday. Live beautifully, love generously, laugh freely. Thanks for being a fantastic friend. I hope ...",
    "Wishing you a day that is as special in every way as you are. Happy Birthday.",
    "You are my friend.",
    "A best friend in my life but much more like family at heart, you are more special to me than I'll ever be able to put into words. I don't know what I did to deserve ...",
    "Wishing my friend a very happy birthday and you don't need to speak it out loud that I'm your best friend too. Love you, dear. Thanks for being a ...",
    "With you I share a truly special and unique bond. Friends like you only come once in a lifetime. I'm so glad you came into my life. Happy Birthday, ...",
    "Happy birthday, dear friend! I wish you to not be afraid of bold choices and keep doing crazy stuff, because life is about trying things that terrify you. May this ...",
    "Happy Birthday Wishes for a Friend. May God shower you with blessings today and always. Happy birthday wishes to my friend! Every step of the way you were ...",
    "Beautiful Happy Birthday Wishes, Quotes, Messages for friends and family.  Wish you a many many happy returns of the day.  On your birthday I wish you success ...",
    "I hope you never stop enjoying the small things in life. Because that's what makes life worth living.",
    "I feel so lucky to have you as my friend.",
    "Happy Birthday to you, my Friend!  ~ If I were a bird, I'd sing for you.  ~ For your Birthday, I'd love to give you a beach where we could make wishes on starfish",
    "Happy birthday may you be blessed with fulfilled dreams and happy thoughts. Birthday Messages to the Friend. Without our friends, life would be very dull.",
    "Happy birthday to my dearest friend, you have always been there for me and I will always be there for you.",
    "Happy birthday! Let's party, BFF! I wish you a very glorious and very bright life ahead. May your life be full of massive success. Our friendship is ...",
    "Funny wishes, touching quotes and meaningful messages let you say happy birthday best friend in a truly special and emotional way to make ...",
    "Happy birthday! I miss you! 15. I miss your smile and everything about you. Here's to wishing you a very happy birthday, best friend!",
    "Happy birthday, my friend. If I could create my life all over again, and pick one friend, it would be you. You are fearless, and I admire you! Thank ...",
    "Today is the start of something beautiful. A new dawn and a fresh start. Exploit and conquer",
    "Happy Birthday, my dear friend! ",
    "Count your life by smiles, not tears. Count your age by friends, not years. I wish you a Happy birthday to cute girlfriend!Happy birthday!",
    "Happy Birthday, I can't imagine my life without your special friendship.  Your friendship means the world to me.",
    "Happy birthday to my ride or die my best friend.  Best friends are never told that they are best friends. They just know and I probably don't need to say it out loud.",
]

